# Generated by Django 4.0.3 on 2022-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
