# Generated by Django 4.0.3 on 2022-04-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
